name: Compile and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install GCC 14, Clang 19, and Valgrind
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-14 clang-19 valgrind

      - uses: actions/checkout@v4

      - name: GCC make test
        run: CC=gcc-14 make clean test

      - name: Clang make test
        run: CC=clang-19 make clean test

      - name: make valgrind
        run: make valgrind
